she_codes_news/news/urls.py
from django.urls import path
from . import views

app_name = 'news'

urlpatterns = [


    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.StoryView.as_view(), name='story'),
    path('add-story/', views.AddStoryView.as_view(), name='newStory'),
    path('story/<int:story_id>/add_comment/', views.add_comment, name='add_comment'),
]

she_codes_news/she_codes_news/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('news/', include('news.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path("create-account/", include("users.urls"))
    
]

she_codes_news/users/urls.py
# users/urls.py
from django.urls import path
from .views import CreateAccountView

app_name ='users'

urlpatterns = [    
    path('create-account/', CreateAccountView.as_view(), name='createAccount'),
    ]

she_codes_news/templates/base.html
<!doctype html>
{% load static %}

<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>She Codes News</title>
        <meta name="description" content="">
        <meta name="author" content="Mienke Dreyer">
        <link href="https://fonts.googleapis.com/css?family=Manjari&display=swap" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
        {% block stylesheets %}{% endblock stylesheets %}
    </head>

    <body>
        <header >
            <div id="header-text">
                <a id="header-link" href="{% url 'news:index' %}">
                    <h1>She {Codes} News</h1>
                </a>
            </div>
            <!-- include nav here -->
            {% include './nav.html' %}
        </header>

        {% block content %} {% endblock content %}
    </body>
</html>

she_codes_news/templates/nav.html
<nav>
    <a href="{% url 'news:index' %}">Home</a>
    <!-- <a href="#">Logout</a>
    <a href="#">Login</a>  -->
    {% if request.user.is_authenticated %}
        <a href="#">{{ user.username }}</a>
        <a href="{% url 'logout' %}">Logout</a>
        <br>
        <button><a href="{% url 'news:newStory' %}">Write New Story</a></button>
        

    {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href=" {% url 'users:createAccount' %}">Create Account</a>
        
    {% endif %}

</nav>
<!-- allows nav bar to change, showing only login if needed -->